TradeRecords/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('',TemplateView.as_view(template_name='index.html'),name='index'),
    path('admin/', admin.site.urls),
    path('tradehelper/', include('tradehelper.urls', namespace='tradehelper'), name='tradehelper'),
    path('traderecord/', include('traderecord.urls', namespace='traderecord'), name='traderecord'),
    path('userinfo/',include('userinfo.urls',namespace='userinfo'),name='userinfo'),
    path('api/',include('api.urls',namespace='api'),name='api'),

]
            # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.urls import path, re_path
from .views import mailing
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'api'

urlpatterns = [
    path('mail/<str:key>', mailing, name='mail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

tradehelper/urls.py
from django.urls import path, re_path
from .views import TradeCalculatorFormView

app_name = 'tradehelper'

urlpatterns = [
    path('', TradeCalculatorFormView.as_view(), name='tradecalculatorform'),
]

traderecord/urls.py
from django.urls import path, re_path
from .views import StockRecordsFormView,StockRecordDetailView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'traderecord'

urlpatterns = [
    path('register/', login_required(StockRecordsFormView.as_view(),login_url='userinfo:login'), name='add_record_form'),
    path('display_record/',login_required(StockRecordDetailView.as_view(),login_url='userinfo:login'),name='display'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

userinfo/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UserInfoFormView, UserProfileLoginFormView, logout_user
from django.contrib.auth.decorators import login_required

app_name = 'userinfo'

urlpatterns = [
    path('register/', UserInfoFormView.as_view(), name='registration'),
    path('login/', UserProfileLoginFormView.as_view(), name='login'),
    path('logout/', login_required(logout_user), name='logout'),

]

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon"
      type="image/png"
      href="{% static 'favicon.png' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>
        {% block title_block %}
            Stock
        {% endblock %}
    </title>
    {% block script_block %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Stock</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% block nav_block %}
                    <a class="nav-link" aria-current="page" href="{% url 'tradehelper:tradecalculatorform' %}">TradeCalculator</a>
                    <a class="nav-link" href="{% url 'traderecord:add_record_form' %}">AddRecords</a>
                    <a class="nav-link" href="{% url 'traderecord:display' %}">ViewRecords</a>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown end-0">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                               aria-expanded="false">{{ user.username }}</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Change Password</a></li>
                                <li><a class="dropdown-item" href="#">Change Username</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'userinfo:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <a class="nav-link" href="{% url 'userinfo:registration' %}">Register</a>
                        <a class="nav-link" href="{% url 'userinfo:login' %}">Login</a>
                    {% endif %}
                {% endblock %}


            </div>


        </div>
    </div>
</nav>
{% block body_block %}

    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'banner/stock1.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'banner/stock2.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'banner/stock3.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'banner/stock4.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'banner/stock5.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'banner/stock6.jpg' %}" class="d-block w-100" alt="...">
            </div>

        </div>
    </div>


{% endblock %}







<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
-->
</body>
</html>